P9K_MODE=nerdfont-complete

# NOTE: Commented code is related to disabled RPROMPT.
P9K_DISABLE_RPROMPT=true

P9K_LEFT_PROMPT_ELEMENTS=(dir nvm vcs status)
# P9K_LEFT_PROMPT_ELEMENTS=(dir nvm vcs)
# P9K_RIGHT_PROMPT_ELEMENTS=(status time)

P9K_LEFT_SEGMENT_SEPARATOR_ICON='\uE0B4'
# P9K_RIGHT_SEGMENT_SEPARATOR_ICON='\uE0B6'

P9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON='%F{blue}╭─%f'
P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON="%F{blue}╰%f "

# P9K_RPROMPT_SUFFIX="%F{black}%f"

P9K_PROMPT_ON_NEWLINE=true
P9K_PROMPT_ADD_NEWLINE=true
# P9K_RPROMPT_ON_NEWLINE=true

P9K_NVM_FOREGROUND='black'
P9K_NVM_BACKGROUND='209'

# P9K_TIME_BACKGROUND='black'
# P9K_TIME_FOREGROUND='249'

P9K_DIR_HOME_ICON=
P9K_DIR_DEFAULT_ICON=
P9K_DIR_ETC_ICON=
P9K_DIR_HOME_SUBFOLDER_ICON=
P9K_DIR_SHORTEN_LENGTH=3

P9K_STATUS_VERBOSE=true
P9K_STATUS_OK=false
