POWERLEVEL9K_MODE=nerdfont-complete

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_internet_signal custom_battery_status_joined dir nvm vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B4 '
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B6'

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%f"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\u2570\uf460%f "

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

POWERLEVEL9K_CUSTOM_INTERNET_SIGNAL='custom_internet_signal'
POWERLEVEL9K_CUSTOM_INTERNET_SIGNAL_BACKGROUND='015'

POWERLEVEL9K_CUSTOM_BATTERY_STATUS='custom_battery_level'
POWERLEVEL9K_CUSTOM_BATTERY_STATUS_BACKGROUND='015'

POWERLEVEL9K_NVM_FOREGROUND='black'
POWERLEVEL9K_NVM_BACKGROUND='072'

POWERLEVEL9K_TIME_BACKGROUND='black'
POWERLEVEL9K_TIME_FOREGROUND='249'

POWERLEVEL9K_HOME_ICON=
POWERLEVEL9K_HOME_SUB_ICON=
POWERLEVEL9K_FOLDER_ICON=
POWERLEVEL9K_ETC_ICON=

POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_STATUS_VERBOSE=false
