#!usr/bin/env bash

if is_wsl; then
  # NOTE: This is purely to suppress warnings that UNC paths are not supported.
  cd /mnt/c

  cmd.exe /C 'code --list-extensions' > "$TOPIC/extensions.txt"
  cd - > /dev/null
fi

if is_macos; then
  code --list-extensions > extensions.txt
fi
