#!/usr/bin/env bash

set -e
export DOTFILES="$HOME/.dotfiles"
cd "$DOTFILES"

display_usage_and_exit() {
  echo "dot -- dotfiles management"
  echo ""
  echo "Usage: dot [options]"
  echo ""
  echo "Options:"
  echo "  -e, --edit    Open dotfiles directory for editing"
  echo "  -h, --help    Show this help message and exit"
  echo "  -d, --dump    Update lists of installed packages"
  echo "  -c, --chmod   Make all .sh files executable"
  exit
}

while test $# -gt 0; do
  case "$1" in
    "-h"|"--help")
      display_usage_and_exit
      ;;
    "-e"|"--edit")
      exec "$EDITOR" "$DOTFILES"
      exit
      ;;
    "-d"|"--dump")
      brew bundle dump --force --file="$DOTFILES/topics/brew/Brewfile"
      code --list-extensions > "$DOTFILES/topics/code/extensions.txt"
      exit
      ;;
    "-c"|"--chmod")
      find "$DOTFILES" -type d -exec chmod 755 {} \;
      find "$DOTFILES" -type f -exec chmod 644 {} \;
      find "$DOTFILES" -iname "*.sh" -exec chmod +x {} \;
      find "$DOTFILES" -iname "*.fish" -exec chmod +x {} \;
      find "$DOTFILES/functions" -exec chmod +x {} \;
      find "$DOTFILES/binaries" -exec chmod +x {} \;
      exit
      ;;
    *)
      echo "Invalid option: $1"
      display_usage_and_exit
      ;;
  esac
  shift
done

./init.sh
