#!/usr/bin/env bash

if [[ -f $1 ]]; then
  case $1 in
    *.tar.bz2) tar -jxvf $1 ;;
    *.tar.gz) tar -zxvf $1 ;;
    *.bz2) bunzip2 $1 ;;
    *.gz) gunzip $1 ;;
    *.tar) tar -xvf $1 ;;
    *.tbz2) tar -jxvf $1 ;;
    *.tgz) tar -zxvf $1 ;;
    *.zip) unzip $1 ;;
    *.ZIP) unzip $1 ;;
    *.pax) cat $1 | pax -r ;;
    *.rar) unrar x $1 ;;
    *) echo "'$1' is not supported by extract" ;;
  esac
else
  echo "'$1' is not a valid file"
fi
