#!/usr/bin/env node

const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto("https://www.pivokarlin.cz/");

  console.log(
    "Pivo Karlín",
    await page.evaluate(() =>
      Array.from(
        document
          .getElementById("menuModala")
          .querySelector(".carousel-item:first-child")
          .querySelectorAll(".row")
      ).map(row => row.querySelector("p").firstChild.textContent)
    )
  );

  await page.goto("https://restauraceglobus.cz/poledni-menu/");

  console.log(
    "Restaurace Globus",
    await page.evaluate(() => {
      const daysOfWeek = ["Pondělí", "Úterý", "Středa", "Čtvrtek", "Pátek"];

      return Array.from(
        document.querySelector(".entry-content").querySelectorAll("p")
      )
        .reduce((weeklyMenu, paragraph) => {
          const content = paragraph.firstChild.textContent;

          if (daysOfWeek.includes(content)) {
            return [...weeklyMenu, []];
          }

          if (weeklyMenu.length) {
            return [
              ...weeklyMenu.slice(0, -1),
              [...weeklyMenu[weeklyMenu.length - 1], content]
            ];
          }

          return weeklyMenu;
        }, [])
        [new Date().getDay() - 1].map(meal => meal.replace(/\s+/g, " "));
    })
  );

  await browser.close();
})();
