#!/usr/bin/env node

const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto("https://www.pivokarlin.cz/");

  console.log(
    "Pivo Karlín",
    await page.evaluate(() =>
      Array.from(
        document.querySelectorAll("#menuModala .carousel-item:first-child .row")
      ).map(row => row.querySelector("p").firstChild.textContent)
    )
  );

  await page.goto("https://restauraceglobus.cz/poledni-menu/");

  console.log(
    "Globus",
    await page.evaluate(() => {
      const daysOfWeek = ["Pondělí", "Úterý", "Středa", "Čtvrtek", "Pátek"];

      return Array.from(document.querySelectorAll(".entry-content p"))
        .reduce((weeklyMenu, paragraph) => {
          const content = paragraph.firstChild.textContent;

          if (daysOfWeek.includes(content)) {
            return [...weeklyMenu, []];
          }

          if (weeklyMenu.length) {
            return [
              ...weeklyMenu.slice(0, -1),
              [...weeklyMenu[weeklyMenu.length - 1], content]
            ];
          }

          return weeklyMenu;
        }, [])
        [new Date().getDay() - 1].map(meal => meal.replace(/\s+/g, " "));
    })
  );

  await browser.close();
})();
