alias y='yarn'
alias yt='y test'
alias yyt='y && yt'
alias yb='y build'
alias yyb='y && yb'
alias yl='y lint'
alias yyl='y && yl'
alias ys='y start'
alias yys='y && ys'
alias ya="y add"
alias yad="ya --dev"
alias yap="ya --peer"
alias yui='y upgrade-interactive --latest'
alias lm='(ls -l node_modules; ls -l node_modules/@*) | grep ^l'
