alias y='yarn'
alias yt='y test'
alias yyt='y && yt'
alias yl='y lint'
alias yyl='y && yl'
alias ys='y start'
alias yys='y && ys'
alias ya="yarn add"
alias yad="yarn add --dev"
alias yap="yarn add --peer"
alias yui='y upgrade-interactive --latest'
alias lm='(ls -l node_modules; ls -l node_modules/@*) | grep ^l'
