tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "python@3.9"
brew "glib"
brew "coreutils"
brew "git"
brew "imagemagick"
brew "mas"
brew "moreutils"
brew "neofetch"
brew "poppler"
brew "watchman"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"
cask "alfred"
cask "android-studio"
cask "bitwarden"
cask "discord"
cask "docker"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "google-drive"
cask "keka"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "microsoft-teams"
cask "postman"
cask "spotify"
cask "telegram"
cask "temurin8"
cask "ukelele"
cask "visual-studio-code"
cask "vlc"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "SonicWall Mobile Connect", id: 822514576
mas "Xcode", id: 497799835
